output:
  - platform: gpio
    id: RS485_SE
    pin:
      number: 19
      inverted: True
  - platform: gpio
    id: RS485_EN
    pin:
      number: 17
      inverted: True
  - platform: gpio
    id: RS485_5V_OUTPUT_EN
    pin:
      number: 16
      inverted: True

uart:
  id: uart_modbus
  tx_pin: GPIO22  # TX pin
  rx_pin: GPIO21  # RX pin
  baud_rate: 115200
  stop_bits: 1
  parity: NONE

modbus:
  id: modbus1

modbus_controller:
- id: modbus_device
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10

sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 0 Voltage"
  register_type: holding
  address: 0x1200
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 1 Voltage"
  register_type: holding
  address: 0x1202
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 2 Voltage"
  register_type: holding
  address: 0x1204
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 3 Voltage"
  register_type: holding
  address: 0x1206
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 4 Voltage"
  register_type: holding
  address: 0x1208
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 5 Voltage"
  register_type: holding
  address: 0x120a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 6 Voltage"
  register_type: holding
  address: 0x120c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 7 Voltage"
  register_type: holding
  address: 0x120e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 8 Voltage"
  register_type: holding
  address: 0x1210
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 9 Voltage"
  register_type: holding
  address: 0x1212
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 10 Voltage"
  register_type: holding
  address: 0x1214
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 11 Voltage"
  register_type: holding
  address: 0x1216
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 12 Voltage"
  register_type: holding
  address: 0x1218
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 13 Voltage"
  register_type: holding
  address: 0x121a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 14 Voltage"
  register_type: holding
  address: 0x121c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 15 Voltage"
  register_type: holding
  address: 0x121e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 16 Voltage"
  register_type: holding
  address: 0x1220
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 17 Voltage"
  register_type: holding
  address: 0x1222
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 18 Voltage"
  register_type: holding
  address: 0x1224
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 19 Voltage"
  register_type: holding
  address: 0x1226
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 20 Voltage"
  register_type: holding
  address: 0x1228
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 21 Voltage"
  register_type: holding
  address: 0x122a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 22 Voltage"
  register_type: holding
  address: 0x122c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 23 Voltage"
  register_type: holding
  address: 0x122e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 24 Voltage"
  register_type: holding
  address: 0x1230
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 25 Voltage"
  register_type: holding
  address: 0x1232
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 26 Voltage"
  register_type: holding
  address: 0x1234
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 27 Voltage"
  register_type: holding
  address: 0x1236
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 28 Voltage"
  register_type: holding
  address: 0x1238
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 29 Voltage"
  register_type: holding
  address: 0x123a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 30 Voltage"
  register_type: holding
  address: 0x123c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell 31 Voltage"
  register_type: holding
  address: 0x123e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell average Voltage"
  register_type: holding
  address: 0x1244
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Cell Voltage max diff"
  register_type: holding
  address: 0x1246
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "MOS Temperature"
  register_type: holding
  address: 0x128A
  unit_of_measurement: "C"
  value_type: S_WORD
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Voltage"
  register_type: holding
  address: 0x1290
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001


- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Power"
  register_type: holding
  address: 0x1294
  unit_of_measurement: "W"
  value_type: U_DWORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001
  
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Current"
  register_type: holding
  address: 0x1298
  unit_of_measurement: "A"
  value_type: S_DWORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001
  
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Temperature 1"
  register_type: holding
  address: 0x129C
  unit_of_measurement: "C"
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Temperature 2"
  register_type: holding
  address: 0x129E
  unit_of_measurement: "C"
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Balance Current"
  register_type: holding
  address: 0x12A4
  unit_of_measurement: "mA"
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery SOC"
  register_type: holding
  address: 0x12A6
  unit_of_measurement: "%"
  value_type: U_WORD
  bitmask: 0x00FF
